#!/usr/bin/env python

import sys, os, glob

def main():
    if len(sys.argv) != 2:
        sys.stderr.write('Usage: %s USB_VOLUME_PATH\n' % os.path.dirname(sys.argv[0]))
        sys.exit(1)
    usb_volume = sys.argv[1]
    if not os.path.isdir(usb_volume):
        sys.stderr.write('ERROR: USB volume not found: %s' % usb_volume)
        sys.exit(1)
    installer_app = None
    createinstallmedia = None
    for app in glob.glob('/Applications/Install*.app'):
        cim_chk = '%s/Contents/Resources/createinstallmedia' % app
        if os.path.exists(cim_chk):
            installer_app = app
            createinstallmedia = cim_chk
    if not installer_app or not createinstallmedia:
        sys.stderr.write('OS X Installer not found.\n')
        sys.exit(1)
    cmd = 'sudo "%(createinstallmedia)s" --volume "%(usb_volume)s" --applicationpath "%(installer_app)s" --nointeraction' % locals()
    print cmd

if __name__ == '__main__':
    main()