#!/bin/bash
# Copyright 2016-17 Steven Cooper
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Run cocoaDialog from inside the app bundle.

for _APP_DIR in /Applications $HOME/Applications; do
    _PATH=$_APP_DIR/cocoaDialog.app/Contents/MacOS/cocoaDialog
    if [ -x $_PATH ]; then
        $_PATH "$@"
        exit $?
    fi
done

echo "CocoaDialog.app not found. http://mstratman.github.io/cocoadialog" 1>&2
exit 255
